name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Run Makefile Operations
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install Make
      run: sudo apt-get install -y make

    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.6'

     
     # https://golangci-lint.run/usage/install#other-ci
    - name: Install golangci-lint ${{ env.GOLANGCI_LINT_VERSION }}
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin ${GOLANGCI_LINT_VERSION}

    - name: Install Yaegi ${{ env.YAEGI_VERSION }}
      run: curl -sfL https://raw.githubusercontent.com/traefik/yaegi/master/install.sh | bash -s -- -b $(go env GOPATH)/bin ${YAEGI_VERSION}

    - name: Setup GOPATH
      run: go env -w GOPATH=${{ github.workspace }}/go

    
    - name: Install Go dependencies
      run: go mod tidy    

    - name: Run Makefile commands
      run: |
        make 
        make lint
        make yaegi_test
        make build                       
        make run
