name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Run Makefile Operations
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install Make
      run: sudo apt-get install -y make

    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.6'

    - name: Install Go dependencies
      run: go mod tidy

    - name: Run Makefile commands
      run: |
        make build
        make test
        make lint
        make check
        make run
